import Nav from "@/components/Nav";
import { Provider } from "./Provider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className="flex ">
            <header className="bg-gray-700 p-4 text-white header">
              <Nav />
            </header>
            <main className="p-4">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
